import os
import sys
import subprocess
from datetime import datetime, timezone, timedelta

# IST Timezone (+05:30)
IST = timezone(timedelta(hours=5, minutes=30))

def log_message(msg):
    now_ist = datetime.now(IST).strftime('%Y-%m-%d %H:%M:%S')
    log_line = f"[{now_ist} IST] {msg}"
    print(log_line)
    log_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "daily_automation.log")
    try:
        with open(log_path, "a", encoding="utf-8") as f:
            f.write(log_line + "\n")
    except Exception:
        pass

def run_daily_auto_sync_and_generation(force_regenerate=False):
    agent_dir = os.path.dirname(os.path.abspath(__file__))
    repo_dir = os.path.dirname(agent_dir)
    output_dir = os.path.join(agent_dir, "Output_Notes")
    os.makedirs(output_dir, exist_ok=True)

    today_str = datetime.now(IST).strftime('%Y-%m-%d')
    log_message("=" * 65)
    log_message(f"🚀 Starting Automated Daily 12 PM Notes Check & Sync for: {today_str}")

    # Step 1: Resilient Cloud Pull (Get any notes generated by Cloud VM)
    from uploader import DriveSyncUploader
    uploader = DriveSyncUploader()
    try:
        log_message("☁️ Checking for latest notes from Cloud VM (GitHub)...")
        synced = uploader.sync_from_cloud(output_dir)
        log_message(f"☁️ Cloud sync completed. Files mirrored: {synced}")
    except Exception as e:
        log_message(f"⚠️ Cloud sync notice: {e}")

    # Step 2: Check if today's notes exist
    today_html = os.path.join(output_dir, f"RAS_UPSC_Notes_{today_str}.html")
    today_docx = os.path.join(output_dir, f"RAS_UPSC_Notes_{today_str}.docx")

    notes_exist = os.path.exists(today_html) and os.path.getsize(today_html) > 5000

    if notes_exist and not force_regenerate:
        log_message(f"✅ Notes for today ({today_str}) already exist and are complete!")
        # Ensure Google Drive has the latest copies
        uploader.sync_to_drive(today_html)
        if os.path.exists(today_docx):
            uploader.sync_to_drive(today_docx)
        log_message("📁 Mirrored today's notes to Google Drive desktop folder.")
    else:
        log_message(f"⚡ Today's notes not found on Cloud VM or regeneration requested. Running Local AI Generator for {today_str}...")
        try:
            from main_agent import run_agent
            html_res = run_agent(target_date=today_str, auto_open=False)
            log_message(f"🎉 Notes successfully generated locally: {html_res}")

            # Commit and push to GitHub so Cloud repo is also up-to-date
            log_message("📤 Pushing locally generated notes to GitHub origin/main...")
            subprocess.run(["git", "-C", repo_dir, "add", "RPSC_UPSC_Daily_AI_Agent/Output_Notes/", "RPSC_UPSC_Daily_AI_Agent/Master_Library/"], capture_output=True, timeout=20)
            commit_res = subprocess.run(["git", "-C", repo_dir, "commit", "-m", f"Auto-generate Daily RAS UPSC Notes & Master Wiki for {today_str} [skip ci]"], capture_output=True, text=True, timeout=20)
            if commit_res.returncode == 0:
                push_res = subprocess.run(["git", "-C", repo_dir, "push", "origin", "main"], capture_output=True, text=True, timeout=30)
                if push_res.returncode == 0:
                    log_message("✅ Pushed new notes to GitHub successfully.")
                else:
                    log_message(f"Notice pushing to GitHub: {push_res.stderr.strip()[:100]}")
            else:
                log_message(f"Commit notice: {commit_res.stdout.strip()[:100]}")
        except Exception as gen_err:
            log_message(f"❌ Error during local generation: {gen_err}")

    log_message("🏁 Automated Daily 12 PM Notes Check Finished.")
    log_message("=" * 65)

if __name__ == '__main__':
    force = "--force" in sys.argv
    run_daily_auto_sync_and_generation(force_regenerate=force)
